# Lab 4 Multi-variable linear regression

In [ ]:
%tensorflow_version 1.x
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

### Matrix 없이 풀어서 작성
- 권장되는 tf 사용법 아님
- 연습/확인용

In [ ]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

In [ ]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [ ]:
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b # 예측되는 y값

In [ ]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [ ]:
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5) # 0.00001
train = optimizer.minimize(cost)

In [ ]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [ ]:
for step in range(2001):
    # cost와 hy를 기록
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

## Matrix를 활용한 다중선형회귀

In [ ]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [ ]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3]) # 행 None, 정해지지 않음, 동적
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [ ]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [ ]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [ ]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [ ]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [ ]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  126121.6 
Prediction:
 [[-159.22546]
 [-197.2163 ]
 [-191.33363]
 [-208.02669]
 [-152.1618 ]]
10 Cost:  13.888784 
Prediction:
 [[154.9044 ]
 [180.36964]
 [180.69513]
 [197.10442]
 [135.84653]]
20 Cost:  12.669057 
Prediction:
 [[155.84157]
 [181.52121]
 [181.81673]
 [198.32693]
 [136.73022]]
30 Cost:  12.604082 
Prediction:
 [[155.83118]
 [181.53384]
 [181.81612]
 [198.32741]
 [136.74518]]
40 Cost:  12.539492 
Prediction:
 [[155.81792]
 [181.54295]
 [181.8121 ]
 [198.32416]
 [136.75745]]
50 Cost:  12.475268 
Prediction:
 [[155.80472]
 [181.55206]
 [181.80812]
 [198.32092]
 [136.76968]]
60 Cost:  12.411341 
Prediction:
 [[155.79152]
 [181.56113]
 [181.80411]
 [198.31767]
 [136.78188]]
70 Cost:  12.347745 
Prediction:
 [[155.77838]
 [181.57019]
 [181.80013]
 [198.31444]
 [136.79405]]
80 Cost:  12.284551 
Prediction:
 [[155.76527]
 [181.57921]
 [181.79616]
 [198.31122]
 [136.80618]]
90 Cost:  12.221666 
Prediction:
 [[155.75218]
 [181.5882 ]
 [181.7922 ]
 [198.308  ]
 [136.81828

## Loading data from file

In [ ]:
import numpy as np

In [ ]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [ ]:
# Make sure the shape and data are OK
print(x_data, "\nx_data shape:", x_data.shape)
print(y_data, "\ny_data shape:", y_data.shape)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
x_data shape: (25, 3)
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
y_data shape: (25, 1)


In [ ]:
# tf.set_random_seed(777)  # for reproducibility

In [ ]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [ ]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [ ]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [ ]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [ ]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [ ]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
 [174.62122]
 [175.85483]
 [165.71132]
 [149.44078]
 [191.96628]]
160 Cost: 9.970844 
Prediction:
 [[150.7787 ]
 [186.58641]
 [180.95482]
 [198.2028 ]
 [142.78105]
 [107.78807]
 [148.65315]
 [110.41567]
 [177.08174]
 [167.10016]
 [143.66112]
 [144.50221]
 [185.84798]
 [153.26216]
 [150.2754 ]
 [189.93987]
 [146.25728]
 [177.79918]
 [176.1744 ]
 [157.29411]
 [174.62466]
 [175.85005]
 [165.71591]
 [149.44812]
 [191.96275]]
170 Cost: 9.949581 
Prediction:
 [[150.78568]
 [186.58073]
 [180.9565 ]
 [198.2043 ]
 [142.7735 ]
 [107.78036]
 [148.65771]
 [110.42428]
 [177.07278]
 [167.08986]
 [143.66165]
 [144.49643]
 [185.8498 ]
 [153.26318]
 [150.27786]
 [189.9351 ]
 [146.2543 ]
 [177.80768]
 [176.17834]
 [157.29909]
 [174.62811]
 [175.8453 ]
 [165.72047]
 [149.45543]
 [191.95923]]
180 Cost: 9.928407 
Prediction:
 [[150.7926 ]
 [186.57509]
 [180.95816]
 [198.2058 ]
 [142.76599]
 [107.77266]
 [148.66228]
 [110.43287]
 [177.06384]
 [167.0796 ]
 [143.66222]
 [14

In [ ]:
# Ask my score
print("Your score will be ", sess.run(hypothesis, 
                                      feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[192.41675]]
Other scores will be  [[177.3107 ]
 [174.27881]]


# Queue Runners
- https://www.tensorflow.org/programmers_guide/reading_data (Error 404)

In [ ]:
# filename_queue = tf.train.string_input_producer(
#     ['data-01-test-score.csv', 'data-02-test-score.csv', ...], shuffle=False, name='filename_queue')
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [ ]:
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.


In [ ]:
# Default values, in case of empty columns. Also specifies the type of the decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

In [ ]:
# collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).


In [ ]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [ ]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [ ]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [ ]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [ ]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [ ]:
# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

In [ ]:
x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
x_batch.tolist()

[[73.0, 80.0, 75.0],
 [93.0, 88.0, 93.0],
 [89.0, 91.0, 90.0],
 [96.0, 98.0, 100.0],
 [73.0, 66.0, 70.0],
 [53.0, 46.0, 55.0],
 [69.0, 74.0, 77.0],
 [47.0, 56.0, 60.0],
 [87.0, 79.0, 90.0],
 [79.0, 70.0, 88.0]]

In [ ]:
for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch]) # 배치 데이터 가져오기
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_batch.tolist(), Y: y_batch.tolist()})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  16018.016 
Prediction:
 [[250.20967]
 [248.30519]
 [334.42316]
 [281.50122]
 [257.446  ]
 [331.21152]
 [272.43515]
 [304.18832]
 [318.32965]
 [283.85345]]
10 Cost:  63.2151 
Prediction:
 [[142.65569]
 [142.27571]
 [192.89133]
 [163.81787]
 [145.3193 ]
 [190.18164]
 [160.33997]
 [170.2399 ]
 [183.39139]
 [163.1167 ]]
20 Cost:  58.74292 
Prediction:
 [[141.93582]
 [141.57076]
 [191.91362]
 [162.98753]
 [144.58315]
 [189.23245]
 [159.53436]
 [169.36653]
 [182.45728]
 [162.28308]]
30 Cost:  58.346855 
Prediction:
 [[141.93692]
 [141.57654]
 [191.8845 ]
 [162.9459 ]
 [144.59866]
 [189.22856]
 [159.47997]
 [169.39108]
 [182.42758]
 [162.25873]]
40 Cost:  57.976135 
Prediction:
 [[141.94286]
 [141.58705]
 [191.86192]
 [162.90976]
 [144.61917]
 [189.23102]
 [159.4308 ]
 [169.42165]
 [182.4041 ]
 [162.23991]]
50 Cost:  57.608223 
Prediction:
 [[141.9488 ]
 [141.59753]
 [191.83943]
 [162.87378]
 [144.63963]
 [189.23347]
 [159.38185]
 [169.45215]
 [182.38077]
 [162.22122]]
60 Cost:  57.2

In [ ]:
coord.request_stop()
coord.join(threads)

In [ ]:
# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[193.18117]]
Other scores will be  [[151.1449 ]
 [180.90271]]
