# Tensor Manipulation
- https://www.tensorflow.org/api_guides/python/array_ops

In [ ]:
%tensorflow_version 1.x
import tensorflow as tf
import numpy as np
import pprint

tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

## Simple Array

In [ ]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)

print(t.ndim) # rank
print(t.shape) # shape

print(t[0], t[1], t[-1]) # indexing
print(t[2:5], t[4:-1]) # slicing
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


## 2D Array

In [ ]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)

print(t.ndim) # rank
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


## Shape, Rank, Axis

In [ ]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4], dtype=int32)

In [ ]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()

array([2, 2], dtype=int32)

In [ ]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4], dtype=int32)

In [ ]:
[  # axis = 0
    [  # axis = 1
        [  # axis = 2
            [1,2,3,4],  # axis = 3 or -1
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

## Matmul VS multiply

In [ ]:
matrix1 = tf.constant([[1.,2.], [3.,4.]])
matrix2 = tf.constant([[1.],[2.]])
print("Matrix 1 shape", matrix1.shape)
print("Matrix 2 shape", matrix2.shape)
tf.matmul(matrix1, matrix2).eval()

Matrix 1 shape (2, 2)
Matrix 2 shape (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

In [ ]:
(matrix1*matrix2).eval()

array([[1., 2.],
       [6., 8.]], dtype=float32)

In [ ]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
tf.matmul(matrix1, matrix2).eval()

array([[12.]], dtype=float32)

In [ ]:
(matrix1*matrix2).eval()

array([[6., 6.],
       [6., 6.]], dtype=float32)

## Broadcasting

In [ ]:
# Operations between the same shapes
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval()

array([[5., 5.]], dtype=float32)

In [ ]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.) # [[3., 3.]]
(matrix1+matrix2).eval()

array([[4., 5.]], dtype=float32)

In [ ]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([3., 4.])
(matrix1+matrix2).eval()

array([[4., 6.]], dtype=float32)

In [ ]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3.],[4.]])
(matrix1+matrix2).eval()

array([[4., 5.],
       [5., 6.]], dtype=float32)

## Random values for variable initializations 

In [ ]:
tf.random_normal([3]).eval() # 정규분포로부터 무작위 추출

array([ 0.22505239, -0.62999827,  0.7879608 ], dtype=float32)

In [ ]:
tf.random_uniform([2]).eval() # 균둥분포로부터 무작위 추출

array([0.88176095, 0.27710772], dtype=float32)

In [ ]:
tf.random_uniform([2, 3]).eval()

array([[0.0747689 , 0.50834334, 0.44480634],
       [0.02172267, 0.54358506, 0.01938498]], dtype=float32)

## Reduce Mean

In [ ]:
tf.reduce_mean([1, 2], axis=0).eval() # 입력값이 int형이므로 결과도 int형이기 때문에 1.5가 아니다

1

In [ ]:
x = [ # axis = 0
     [1., 2.], # axis = 1 or -1
     [3., 4.]
     ]

tf.reduce_mean(x).eval() # 전체 평균

2.5

In [ ]:
tf.reduce_mean(x, axis=0).eval()

array([2., 3.], dtype=float32)

In [ ]:
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [ ]:
tf.reduce_mean(x, axis=-1).eval()

array([1.5, 3.5], dtype=float32)

## Reduce Sum

In [ ]:
x = [ # axis = 0
     [1., 2.], # axis = 1 or -1
     [3., 4.]
     ]

In [ ]:
tf.reduce_sum(x).eval()

10.0

In [ ]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [ ]:
tf.reduce_sum(x, axis=-1).eval()

array([3., 7.], dtype=float32)

In [ ]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

## Argmax with axis
- max 값의 위치 반환

In [ ]:
x = [ # axis = 0
     [0, 1, 2], # axis = 1
     [2, 1, 0]
     ] 
tf.argmax(x, axis=0).eval()

array([1, 0, 0])

In [ ]:
tf.argmax(x, axis=1).eval()

array([2, 0])

In [ ]:
tf.argmax(x, axis=-1).eval()

array([2, 0])

## Reshape

In [ ]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [ ]:
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

### squeeze, expand_dims

In [ ]:
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2], dtype=int32)

In [ ]:
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]], dtype=int32)

## One hot

In [ ]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [ ]:
# rank가 자동적으로 2 > 3 이 된다
t = tf.one_hot([[0], [1], [2], [0]], depth=3)

# 다시 rank를 2로
tf.reshape(t, shape=[-1, 3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

## Casting

In [ ]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4], dtype=int32)

In [ ]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0], dtype=int32)

## Stack

In [ ]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [ ]:
tf.stack([x, y, z], axis=0).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [ ]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [ ]:
tf.stack([x, y, z], axis=-1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

## Ones like and Zeros like

In [ ]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

## Zip


In [ ]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [ ]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


## Transpose

In [ ]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
print(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [ ]:
t1 = tf.transpose(t, [1, 0, 2])
print(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [ ]:
t = tf.transpose(t1, [1, 0, 2])
print(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [ ]:
t2 = tf.transpose(t, [1, 2, 0]) # (2, 2, 3) > (2, 3, 2)
print(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])


In [ ]:
t = tf.transpose(t2, [2, 0, 1])
print(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])
